### ISSUE TITLE
privilege to execute dbms_mle

### ISSUE THREAD

**Issue by zakpex** [stefandobre/apex-mle-demo#2]
since which release we need to grant 
`grant EXECUTE ON JAVASCRIPT to app_schema;`

**Comment by stefandobre** [comment]
Hi zakpex,
Generally, this is done automatically when provisioning a new workspace + schema through APEX.
But there's currently a bug which causes the revoking of this grant upon APEX upgrade.
For now, you'll need to manually re-grant it after upgrade. Either through SYS or ADMIN.

**Comment by zakpex** [comment]
thanks
